# Setup
title:               KING blog
tagline:             'KING Is Not Genera, but it will be'
description:         >
                     (defλ Ξ<br>
                     &nbsp;&nbsp;[x]<br>
                     &nbsp;&nbsp;(χ <br>
                     &nbsp;&nbsp;&nbsp;&nbsp;(φ? x) x<br>
                     &nbsp;&nbsp;&nbsp;&nbsp;(∪ <br>
                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ζ? x)<br>
                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Λ? (α x))) (Ξ (Λ x (ω x)))<br>
                     &nbsp;&nbsp;&nbsp;&nbsp;(⊌? x) (↦ Ξ x))) <br><br>
                     (≝ eval Ξ)
url:                 https://acgollapalli.github.io/KING-blog
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              A. Caleb Gollapalli
  url:               https://acgollapalli.github.io/KING-blog
  email:             acgollapalli@protonmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
