# Setup
title:               KING blog
tagline:             'KING Is Not Genera, but it will be'
description:         'KING Is Not Genera will be KING OS'
url:                 https://acgollapalli.github.io/KING-blog/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              A. Caleb Gollapalli
  url:               https://acgollapalli.github.io/KING-blog/
  email:             acgollapalli@protonmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
